#ifndef	__MTK_GDMA_H__
#define	__MTK_GDMA_H__

#define	MTK_GDMA_SRC_ADDR(x)		(0x00 + (x) * 0x10)
#define	MTK_GDMA_DST_ADDR(x)		(0x04 + (x) * 0x10)
#define	MTK_GDMA_CTRL0(x)		(0x08 + (x) * 0x10)
#define	MTK_GDMA_CTRL0_TX_MASK		0xffff
#define	MTK_GDMA_CTRL0_TX_SHIFT		16
#define	MTK_GDMA_CTRL0_SRC_ADDR_FIXED	(1U << 7)
#define	MTK_GDMA_CTRL0_DST_ADDR_FIXED	(1U << 6)
#define	MTK_GDMA_CTRL0_BURST_MASK	0x7
#define	MTK_GDMA_CTRL0_BURST_SHIFT	3
#define	 MTK_GDMA_CTRL0_BURST_SIZE_WD1	0
#define	 MTK_GDMA_CTRL0_BURST_SIZE_WD2	1
#define	 MTK_GDMA_CTRL0_BURST_SIZE_WD4	2
#define	 MTK_GDMA_CTRL0_BURST_SIZE_WD8	3
#define	 MTK_GDMA_CTRL0_BURST_SIZE_WD16	4
#define	MTK_GDMA_CTRL0_DONE_INT		(1U << 2)
#define	MTK_GDMA_CTRL0_ENABLE		(1U << 1)
#define	MTK_GDMA_CTRL0_SW_MODE		(1U << 0)
/* For MT7620, MT76[2|8]8 */
#define	MTK_GDMA_CTRL0_CURR_MASK	0xff
#define	MTK_GDMA_CTRL0_CURR_SHIFT	8

#define	MTK_GDMA_CTRL1(x)		(0x0c + (x) * 0x10)
#define	MTK_GDMA_CTRL1_REQ_MASK		0x3f
#define	MTK_GDMA_CTRL1_SRC_REQ_SHIFT	16			
#define	MTK_GDMA_CTRL1_DST_REQ_SHIFT	8
#define	MTK_GDMA_CTRL1_NEXT_MASK	0x1f
#define	MTK_GDMA_CTRL1_NEXT_SHIFT	3
#define	MTK_GDMA_CTRL1_COHERENT		(1U << 2)
#define	MTK_GDMA_CTRL1_FAIL		(1U << 1)
#define	MTK_GDMA_CTRL1_MASK		(1U << 0)
/* For MT7620, MT76[2|8]8 */
#define	MTK_GDMA_CTRL1_SEG_MASK		0xf
#define	MTK_GDMA_CTRL1_SEG_SHIFT	22
#define MTK_GDMA_CTRL1_CONT_MODE_EN	(1U << 14)

#define	MTK_GDMA_UNMASK_INT		0x200
#define	MTK_GDMA_DONE_INT		0x204

#define	MTK_GDMA_GCT			0x220
#define	MTK_GDMA_GCT_CHAN_MASK		0x3
#define	MTK_GDMA_GCT_CHAN_SHIFT		3
#define	MTK_GDMA_GCT_VER_MASK		0x3
#define	MTK_GDMA_GCT_VER_SHIFT		1
#define	MTK_GDMA_GCT_ARBIT_RR		(1U << 0)

#define	MTK_GDMA_REQSTS			0x2a0
#define	MTK_GDMA_ACKSTS			0x2a4
#define	MTK_GDMA_FINSTS			0x2a8

#endif	/* __MTK_GDMA_H__ */
